# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ece29b9a05806d952f9d89552a290f8452635f080230ae1ddd0660fd8d478b0fc1635e6ff987467755e361ff26e7ca3c1014bdccabe86b0132cc1099b7c41f28

test:
  secret_key_base: 416282cfeec6222e8f4e6add4efe699c68eb6b3eca25131cc1e26145d1f5f65e840877d44bb32ee15eb84256c293a5c1fe1bf94213c7fe047901bf7cc8c1f19b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
